name: Test and Build Application

on:
  pull_request:
    branches:
      - test
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v5

      - name: Install UV package manager
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.10"

      - name: Install Python
        run: uv install python

      - name: Install dependencies
        run: uv sync --locked

      - name: Test Application
        run: uv run pytest

      - name: Results
        if: success()
        run: echo "All test passed proceed to build"

      